---
title: "Contents"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
#### This work is from the Bodenmiller lab IMC Data Analysis Workflow written by Nils, Vito, Michelle, Daniel and Jonas and publicly available online at https://bodenmillergroup.github.io/IMCDataAnalysis/

#### Dataset:NASH/NAFLD/WT mouse livers stained with the UniBe mouse IMC panel

- [Data preparation](0_prep_data.html):
    - construct `SpatialExperiment`
    - single-cell processing
    - read in images
    
- [Quality control mask](1_QC_mask.html):
    - Segmentation quality control
    - Image and cell level quality control
    
- [Batch_effect_correction](2_batch_effect_correction.html):
    - fastMNN correction
    - harmony correction
    - Seurat correction
    
- [Dimensionality reduction](3_dim_red.html):
    - clustering approaches
    
- [Cell phenotyping](4_cell_annotation.html):
    - Classify cells with Shiny app
    - Train cell classifier
    
- [Single cell visualization](5_sc_vis.html):
    - Cell-type level
    - Sample level
    - More examples
    
- [Image visualization](6_img_vis.html):
    - Pixel visualization
    - Cell visualization
    - Adjusting plot annotations
    - Displaying, saving and returning images
    
- [Spatial visualization](7_spatial_vis.html):
    - Spatial interaction graphs
    - Spatial visualization
    - Spatial community analysis
    - Cellular neighborhood analysis
    - Spatial context analysis
    - Patch detection
    - Interaction analysis
